# Generated by Django 3.1 on 2022-09-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0002_msg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
