# Generated by Django 4.1.1 on 2022-09-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0004_alter_announcement_id_alter_answer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='message_image/'),
        ),
        migrations.AlterField(
            model_name='msg',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
